spring:
  application:
    name: bs-user-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    url: jdbc:mysql://router.liuhongchen.com:3306/bs_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: router.liuhongchen.com
    database: 0
    port: 6379
    user: root
    password: 123456
    timeout: 3000
  rabbitmq:
    host: router.liuhongchen.com
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://router.liuhongchen.com:7700
  sleuth:
    sampler:
      percentage: 1.0

mybatis:
  type-aliases-package: com.liuhongchen.bscommonmodule.pojo
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 15001

eureka:
  client:
    service-url:
      defaultZone: http://router.liuhongchen.com:7776/eureka/

logging:
  level:
    root: info

#不添加这一项，每次访问都会报异常,zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false