spring:
  application:
    name: bs-user-consumer
  redis:
    host: 192.168.1.180
    database: 0
    port: 6379
    user: root
    password: 123456
    timeout: 3000
#  zipkin:
#    base-url: http://localhost:7700
#  sleuth:
#    sampler:
#      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7776/eureka/
    fetch-registry: true
server:
  port: 15051

feign:
  hystrix:
    enabled: false

#要以被负载均衡的模块的名字开始，默认是轮询
#bs-user-provider:
#  ribbon:
#    NFLoadBalanceRuleClassName: com.netflix.loadBalancer.RandomRule

#logging:
#  level:
#    root: info
