spring:
  application:
    name: bs-pay-consumer

  redis:
    host: router.liuhongchen.com
    database: 0
    port: 6379
    user: root
    password: 123456
    timeout: 3000
  kafka:
    producer:
      bootstrap-servers: router.liuhongchen.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  zipkin:
    base-url: http://router.liuhongchen.com:7700
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: router.liuhongchen.com
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://router.liuhongchen.com:7776/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
server:
  port: 15251

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 500
#要以被负载均衡的模块的名字开始，默认是轮询
#bs-user-provider:
#  ribbon:
#    NFLoadBalanceRuleClassName: com.netflix.loadBalancer.RandomRule

logging:
  level:
    root: info

